### PR TITLE
Use i128 to represent integers

### PR DESCRIPTION
**Pull request by cpcloud**
This is one approach to solving the problem of containing a value of all
supported integer types in a single type.

In this approach we store all values in a large type so that both signed and
unsigned values can be contained a single type.

An alternative approach would be to use an `enum` with
either of the following approaches:
  1. Two variants (`u64` and `i64`) used for each of the unsigned and signed
     categories of values, respectively.
  1. An enum with a variant for each integer type.

The latter of these seems like a lot of additional complexity for minimal
benefit, especially since this change only affects parsing.

Generated code will not see any use of `i128`.

### CODE REVIEW

**Comment by lovesegfault** [comment]
The enum approach is better since 128-bit integers do not have a stable ABI, IMO.

**Comment by cpcloud** [comment]
@lovesegfault sounds good to me. I'll fix up the PR the week after Christmas or sooner if I get some time.

**Comment by cpcloud** [comment]
Picking this back up and implementing the enum approach.

**Comment by cpcloud** [comment]
@magnet @lovesegfault can y'all review?

**Comment by magnet** [comment]
> The enum approach is better since 128-bit integers do not have a stable ABI, IMO.

I don't understand the problem of ABI here, since this is only used internally in `butte-build` and we don't use FFI?

I kinda liked the simplicity of that approach :confused: (I see this discussion is old, but I hadn't seen this it earlier, sorry)

**Comment by lovesegfault** [comment]
It was mostly out of fear, me and @cpcloud talked a (long) while ago about this PR and had both agreed the simplicity of the 128bit-based impl trumped any concerns over ABI for our uses. 

I'm fine with this impl, and fine if Phil wants to revert to the original strategy

**Comment by cpcloud** [comment]
Ok, I'm going to move this back to `i128` as it was much simpler. We can of course revisit if this issue were to come up in the future.

**Comment by cpcloud** [comment]
Merging on green.

**Pull request merged**
