### PR TITLE
Fork flatbuffers

### PR DESCRIPTION
**Pull request by magnet**
Fork the flatbuffers Rust implementation inside butte-rs
    
This is a first step to take ownership of the flatbuffers implementation and fix the design and unsafety issues.
The commit history of the Rust flatbuffers crate is also imported.

It's possible to host this fork flatbuffers outside of butte but I believe it would make sense to have it in the same repo. It would also be possible to fix the safety issues in the original repo, but a mono-repo for flatbuffers is impractical and we're looking to break backwards-compatibility (the current flatbuffers implementation is fundamentally unsafe).

The plan is to still expose an unsafe interface (but only with unsafe methods) which can discard the bound checks (potentially useful for trusted data, but the user has to uphold the invariant that the data is correctly laid out) -- but the safe interface will be the prime API we're going to work on. The plan is for it to return fallible types (behind a `Result`) and provide an interface that's generic over borrowing (so that we may use `Bytes` or `BytesMut` to avoid exposing lifetimes, which is useful for the Tonic glue code)

### CODE REVIEW

**Comment by magnet** [comment]
This is currently failing because you go back to 1.34 for Rust compat (and the alloc feature wasn't stabilized by then).  Is there a reason for that?  I believe 1.39 is a very important milestone and I don't really know why new projects should try to be compatible with older versions.

**Comment by cpcloud** [comment]
No particular reason other than trying to support as old a version as reasonably possible. Totally fine to bump the version to 1.39. I can also do that in a separate PR.

**Comment by lovesegfault** [comment]
Merged MSRV bump to 1.39 together with the derive_more vbump, cc @magnet.

**Comment by magnet** [comment]
I'll update the code to appease Clippy

**Comment by magnet** [comment]
Currently the `butte` module is a Rust port `flatc` compiler + AST as a lib (we can imagine having a binary compiler later), while this fork of the flatbuffers crate is meant to become the shared utils for runtime. 

Regarding the naming of that fork, I'm not sure `butte-flatbuffers` make much sense. While it's the part of butte that will be used at runtime (along with the generated code), I wouldn't call it `butte-runtime` because it's just a set of shared utils, not really a runtime.

Tonic has a similar build + runtime crate -- if we were to adopt the same convention the current `butte` module would become `butte-build` and this `butte-flatbuffers` crate would become `butte`. There's still significant work to make it safe [for the time being, we could just make all the functions `unsafe`, with the invariant that the buffer they work on is a valid flatbuffer that must be uphold by the caller], so I'm not sure it makes sense to do that *now* but just thought for food.

**Comment by cpcloud** [comment]
@magnet Agreed. I originally named the current `butte` as `butte-build`, and changed it before I knew we were going to fork. We can do the renaming now or whenever, but I think it might be better to do it ASAP so we don't break stuff later on. Thoughts? I'll open an issue.

**Comment by cpcloud** [comment]
In any event, merging this PR. Thanks!

**Review by cpcloud — COMMENTED** [review]
LGTM.

**Pull request merged**
