### PR TITLE
Bump MSRV

### PR DESCRIPTION
**Pull request by cpcloud**
cc @magnet

### CODE REVIEW

**Comment by cpcloud** [comment]
Hm, not entirely sure why CI isn't running.

**Comment by cpcloud** [comment]
Suspicious that just code coverage is running. Looks like there's a sizable queue building up.

**Comment by magnet** [comment]
Wouldn't the other build checks be in hold if they were queued up?

**Comment by cpcloud** [comment]
Yeah, but they'd show up as queuing in the list of checks.

**Pull request merged**
