### PR TITLE
Fix field metadata parsing

### LINKED ISSUE #23: Parser chokes on field attributes
The current parser seems unable to accept field attributes (apparently named metadata in `butte-build`?). I had a quick try to fix this, but I have no experience with nom 5. @cpcloud maybe you have an idea?

Here's an example of a schema failing to parse:
```
table HelloReply {
  message: string (required);
}
```

### PR DESCRIPTION
**Pull request by cpcloud**
Closes #23.

### CODE REVIEW

**Comment by magnet** [comment]
Oh I just wrote a similar PR at https://github.com/butte-rs/butte/compare/master...magnet:fix/field_attributes_parsing ! :smile:. Yours is more complete though -- thanks!

**Comment by magnet** [comment]
Just a small question: what do attributes refer to in `butte-build`? The flatbuffers spec seems to refer to what you call `metadata` as `attributes`.

**Comment by cpcloud** [comment]
@magnet The naming comes from the schema grammar here: https://google.github.io/flatbuffers/flatbuffers_grammar.html combined with the documentation on attributes here: https://google.github.io/flatbuffers/flatbuffers_guide_writing_schema.html.

My reading of it is that metadata is the collection of attributes and their (optional) values. There are a few builtin attributes like `required`, `deprecated`, etc and there are user-defined attributes which must be declared using the `attribute` syntax.

**Comment by magnet** [comment]
@cpcloud @lovesegfault any news on the review?  It looks good to me.  I can be a reviewer if that helps.

**Pull request merged**
