### PR TITLE
Don't require optional fields

### LINKED ISSUE #47: "missing required field value" with optional value
Hi,

I'm not quite sure if this is a bug or if I'm doing something wrong. With the following definition:

```
table Hello {
    value: string;
}
```

I get a the `Option` and a `Default` implementation as expected:
```rust
pub struct HelloArgs<'a> {
    pub value: Option<butte::WIPOffset<&'a str>>,
}
impl<'a> Default for HelloArgs<'a> {
  fn default() -> Self {
    Self { value: None }
  }
}
```

But it now fails on runtime with the `missing required field value` error. I think it is related to the fact that the `create()` method only calls the internal `add_value()` method if the field is `Some` but the `finish()` step fails because `Hello::VT_VALUE` is not set.

```rust
        if let Some(x) = args.value {
            builder.add_value(x);
        }
```
...`add_value()` sets the `Hello::VT_VALUE` slot...
```rust
        self.fbb.required(o, Hello::VT_VALUE, "value");
```

### PR DESCRIPTION
**Pull request by reyk**
Fixes butte-rs/butte#47

### CODE REVIEW

**Review by lovesegfault — APPROVED** [review]
Looks good to me, r+ after adding tests

**Review by cpcloud — CHANGES_REQUESTED** [review]
@reyk Thanks for doing this! Can you add a test? Then I'll approve and merge.

**Comment by reyk** [comment]
Is the "Code Coverage" test failing because of the `rustfmt` call in `butte_build::compile_fbs`? The same command works fine here.

**Comment by reyk** [comment]
Hi, is there anything missing from my side?

**Comment by lovesegfault** [comment]
Nope, I think me and @cpcloud have just been busy surviving the apocalypse :sweat_smile:

**Comment by reyk** [comment]
Thanks for merging, I hope you’re well!

**Pull request merged**
